### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by nanuxbe** [drf-forms/drf-schema-adapter#3]
Hi all,

we discussed the fact that drf-forms was a temporary name and that we should find a better name, here are a few proposals:

- drf_admin_toolkit
- drf_fe_toolkit
- drf_fe_adapters

**Comment by adrienbrunet** [comment]
What about drf_schema_generator? drf_schema_adapters?

**Comment by nanuxbe** [comment]
I like drf_shema_adapters

**Comment by nanuxbe** [comment]
Unless somebody opposes to this name in the next 48h, I'll publish the package under that name on pypi.

**Comment by nostalgiaz** [comment]
drf_schema_adapters is fine for me
