### ISSUE TITLE
Support for __all__ in fields definition

### ISSUE THREAD

**Issue by xnegativx** [drf-forms/drf-schema-adapter#38]
Hi,
Using the __all__ keyword in serializer fields definition won't work. 
The issue is coming from using serializer.Meta.fields in several places. DRF is using serializer.fields.items() instead which seems to handle it correctly. Is there a specific reason not to use it ? (I'll try to have a PR tomorrow for it)

**Comment by nanuxbe** [comment]
Hi,
The Django core team had already started to "look down" on using `__all__` (ie: forms) so we've simply not tought of looking into it.
If using `serializer.fields.items()` doesn't break anything, the PR will be most welcomed :-)

**Comment by nanuxbe** [comment]
this has been fixed
