### ISSUE TITLE
angular2 support?

### ISSUE THREAD

**Issue by zerox12311** [drf-forms/drf-schema-adapter#54]
Hi, I found this library.
But angular2 is not support, angular2 now have a library which call ngx-formly
Do you like to support this library?

**Comment by nanuxbe** [comment]
Ping @adrienbrunet  @adrienmindee
Is that something you'd be willing to work on?

**Comment by adrienmindee** [comment]
Hi tehre, sadly, I'm no longer working with angular. I moved on the vue/react side for now. :/ I'm a bit rusty on angular, I won't be able to help properly.

**Comment by nanuxbe** [comment]
I am closing this issue for now then since neither you or me have kept up with angular.
If anyone with angular knowledge is willing to take this on, please, feel free to re-open.
