### ISSUE TITLE
Recent version update (2.0.8) broke something

### ISSUE THREAD

**Issue by hoermannpaul** [drf-forms/drf-schema-adapter#66]
First: Big thanks for this package, great helper and saves us unlimited hours.

If i start django / run tests following happens:
```
  ...
  File "/path/to/package/.venv/lib/python3.9/site-packages/drf_auto_endpoint/endpoints.py", line 235, in get_url
    if self.url is not None:
AttributeError: 'Endpoint' object has no attribute 'url'
```
Adding `url=None` to BaseEndpoint class fixes the problem. Using `hasattr(self, "url")` on line 235 would also be a possible fix.

**Comment by nanuxbe** [comment]
Frst of all, thank you for your patience.

You can either use the new version (:point_up: merge above) or provide a `url` directly in your endpoint.
