### ISSUE TITLE
angular-formly Does not support the read_only option will cause failure

### ISSUE THREAD

**Issue by qianxuanyon** [drf-forms/drf-schema-adapter#71]
surefire  http://angular-formly.com/#!/example/integrations/ui-select-angular-1-4

Increase read_only: false Cause failure
[
  {
    "key": "singleOption",
    "type": "ui-select-single",
    "templateOptions": {
      "optionsAttr": "bs-options",
      "ngOptions": "option[to.valueProp] as option in to.options | filter: $select.search",
      "label": "Single Select",
      "valueProp": "id",
      "labelProp": "label",
      "placeholder": "Select option",
      "description": "Template includes the allow-clear option on the ui-select-match element",
      "options": [
        {
          "id": 1,
          "label": "Option 1"
        },
        {
          "id": 2,
          "label": "Option 2"
        },
        {
          "id": 3,
          "label": "Option 3"
        }
      ]
    }
  },
  {
    "key": "select2Option",
    "type": "ui-select-single-select2",
    "templateOptions": {
      "optionsAttr": "bs-options",
      "ngOptions": "option[to.valueProp] as option in to.options | filter: $select.search",
      "label": "Single Select (select2)",
      "valueProp": "id",
      "labelProp": "label",
      "placeholder": "Select option",
      "options": [
        {
          "id": 1,
          "label": "Option 1"
        },
        {
          "id": 2,
          "label": "Option 2"
        },
        {
          "id": 3,
          "label": "Option 3"
        }
      ]
    }
  },
  {
    "key": "multipleOption",
    "type": "ui-select-multiple",
    "templateOptions": {
      "optionsAttr": "bs-options",
      "ngOptions": "option[to.valueProp] as option in to.options | filter: $select.search",
      "label": "Multiple Select",
      "valueProp": "id",
      "labelProp": "label",
      "placeholder": "Select options",
      "options": [
        {
          "id": 1,
          "label": "Option 1"
        },
        {
          "id": 2,
          "label": "Option 2"
        },
        {
          "id": 3,
          "label": "Option 3"
        }
      ]
    }
  },
  {
    "key": "singleOptionAsync",
    "type": "ui-select-single-search",
    "templateOptions": {
      "optionsAttr": "bs-options",
      "ngOptions": "option[to.valueProp] as option in to.options | filter: $select.search",
      "label": "Async Search",
      "valueProp": "formatted_address",
      "labelProp": "formatted_address",
      "placeholder": "Search",
      "options": [],
      "refreshDelay": 0
    }
  }
]

**Comment by nanuxbe** [comment]
I am sorry but I don't understand what you mean. I cannot see any `ready_only' in the above JSON.

Also, since I have been so slow to answer, I am not sure this is still relevant, I am therefore closing this. Feel free to re-open
