### ISSUE TITLE
must add drf_auto_endpoint to INSTALLED_APPS

### ISSUE THREAD

**Issue by hosler** [drf-forms/drf-schema-adapter#72]
Forgive me if I missed it, but I couldn't find anywhere in the docs that says to put 'drf_auto_endpoint' in INSTALLED_APPS. This entry is required if you are using endpoints.py file.

**Comment by nanuxbe** [comment]
:point_up: would that make things more clear and do you think it should be mentioned elsewhere?

For the sake of clarity, `drf_auto_endpoint` only needs to be added to `INSTALLED_APPS` if you want to use the auto-divery/register feature. To be fair, personally, this is indeed something I want 90% of the time ;-)

**Comment by hosler** [comment]
looks good to me

**Comment by nanuxbe** [comment]
Thanks, I'll close this then
