### ISSUE TITLE
Can't install version >=3.0.1 from pypi anymore

### ISSUE THREAD

**Issue by wasmitnetzen** [drf-forms/drf-schema-adapter#79]
Hi,

since [4d437c1](https://github.com/drf-forms/drf-schema-adapter/commit/4d437c10bcb4406d2cb7a7e8ab1b8fd2d2c1a5ea) and the release of version 3.0.1, this package can't be installed anymore with pip from pypi, since [pip#5571](https://github.com/pypa/pip/pull/5571) requires that packages from PyPI must only install dependencies from PyPI. Installation thus fails with

```
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
```

This can be worked around of course by not installing the package from PyPI, but I would guess this is not the intended outcome.

**Comment by nanuxbe** [comment]
Indeed, not the intended outcome...

The work around is (as you said, but I'm spelling it out for the sake of others who might run into the issue:

```bash
pip install git+https://github.com/ixmatus/inflector@ef5c19dc2aa8df5e6b4c452ff2d9b54ec41a04a8#egg=Inflector
pip install drf-schema-adapter
```

I'll up date the release and add a note in the readme about Python `3.11` compatibility (which is the reason that requirement is there)

**Comment by nanuxbe** [comment]
https://pypi.org/project/drf-schema-adapter/3.0.4/

Should solve the issue. With the caveat of the extra step for python 3.11
